### PR TITLE
Support for VLAN feature and re-arranging code for existing intf_app module.

### PR DESCRIPTION
**Pull request by justinejose91**

### CODE REVIEW

**Comment by jeffyin-dell** [comment]
@justinejose91 -- do you want to hold off on this PR until the tagged-member deletion issue can be done?

**Comment by justinejose91** [comment]
yes @jeff-yin , I just raised so that people can review it.

**Comment by jeffyin-dell** [comment]
@justinejose91 -- status of this merge? member-deletion issue should be fixed, right? Is this ready for final review and merge? #154 is depending on this merge as well.
Also, looks like you need to resolve some merge conflicts.

**Comment by justinejose91** [comment]
I am working on merge conflict.

**Pull request closed without merging**
