### PR TITLE
Support stp for port-channel interfaces and fix display issues

### PR DESCRIPTION
**Pull request by spenugondaa**
- New command spanning-tree sub tree under port-channel interface to configure stp
- fix port-role/edge-port display issues in renderer
- look at state container for displaying vst information

~~~text
sonic(config)# interface PortChannel 4
sonic(conf-if-po4)#
  end            Exit to the exec Mode
  exit           Exit from current mode
  fallback       Configure LACP fallback
  ip             Interface Internet Protocol config commands
  ipv6           Interface Internet Protocol config commands
  link           Interface link
  mclag          Configure MCLAG interface
  min-links      Configure the minimum number of links in a PortChannel
  mtu            Configure MTU
  nat-zone       NAT Zone
  no             Negate a command or set its defaults
  shutdown       Disable the interface
  spanning-tree  Configure spanning tree on port-channel
  switchport     Configure switchport parameters
sonic(conf-if-po4)# spanning-tree
  bpdufilter     Spanning-tree BPDU filter on the port-channel
  bpduguard      Enables bpdu guard on the port-channel
  cost           Set the port level cost
  enable         Enables spanning-tree on the port-channel
  guard          Configure spanning tree guard on port-channel
  link-type      Set link type of the port-channel
  port           Set Spanning tree port
  port-priority  Set the port level priority
  portfast       Enables portfast on the port-channel
  uplinkfast     Enables uplink fast on the port-channel
  vlan           Configure spanning tree on port-channel for VLAN
sonic(conf-if-po4)# spanning-tree bpdufilter enable
Success
sonic(conf-if-po4)# spanning-tree bpdufilter disable
Success
sonic(conf-if-po4)# spanning-tree bpduguard port-shutdown
Success
sonic(conf-if-po4)# spanning-tree cost 100
Success
sonic(conf-if-po4)# spanning-tree enable
Success
sonic(conf-if-po4)# spanning-tree uplinkfast
Success
sonic(conf-if-po4)# spanning-tree portfast
Success
sonic(conf-if-po4)# spanning-tree port-priority 10
Success
sonic(conf-if-po4)# spanning-tree port type edge
Success
sonic(conf-if-po4)# spanning-tree link-type
auto           point-to-point shared
sonic(conf-if-po4)# spanning-tree link-type auto
Success
sonic(conf-if-po4)# spanning-tree guard root
Success

CONFIG-DB 

127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 1) "portfast"
 2) "true"
 3) "uplink_fast"
 4) "true"
 5) "link_type"
 6) "auto"
 7) "enabled"
 8) "true"
 9) "root_guard"
10) "true"
11) "bpdu_guard"
12) "false"
13) "bpdu_filter"
14) "global"
15) "bpdu_guard_do_disable"
16) "false"
17) "priority"
18) "10"
19) "edge_port"
20) "true"

SHOW COMMANDS

sonic(conf-if-Ethernet4)# do show spanning-tree
Spanning-tree Mode: RPVST

VLAN 4 - RSTP instance 0
------------------------------------------------------------------------------------------------------------

RSTP (IEEE 802.1w) Bridge Parameters:

Bridge            Bridge    Bridge    Bridge    tx
Identifier        MaxAge    Hello     FwdDly    Hold
hex               sec       sec       sec       cnt
800490b11cf4a3a7  20        2         15

RootBridge        RootPath  DesignatedBridge  Root        Max  Hel  Fwd
Identifier        Cost      Identifier        Port        Age  lo   Dly
hex                         hex                           sec  sec  sec
800490b11cf4a3a7  0         800490b11cf4a3a7  Root        20   2    15

RSTP (IEEE 802.1w) Port Parameters:
Port            Prio Path      P2P Edge BPDU   Role        State      Designa-   Designated
Num             rity Cost      Mac Port Filter                        ted cost   bridge
PortChannel4    128  4         Y   Y    Y                  DISABLED   0          0000000000000000
sonic(conf-if-Ethernet4)#

sonic(conf-if-Ethernet4)# do show spanning-tree vlan 4
Spanning-tree Mode: RPVST

VLAN 4 - RSTP instance 0
------------------------------------------------------------------------------------------------------------

RSTP (IEEE 802.1w) Bridge Parameters:

Bridge            Bridge    Bridge    Bridge    tx
Identifier        MaxAge    Hello     FwdDly    Hold
hex               sec       sec       sec       cnt
800490b11cf4a3a7  20        2         15

RootBridge        RootPath  DesignatedBridge  Root        Max  Hel  Fwd
Identifier        Cost      Identifier        Port        Age  lo   Dly
hex                         hex                           sec  sec  sec
800490b11cf4a3a7  0         800490b11cf4a3a7  Root        20   2    15

RSTP (IEEE 802.1w) Port Parameters:
Port            Prio Path      P2P Edge BPDU   Role        State      Designa-   Designated
Num             rity Cost      Mac Port Filter                        ted cost   bridge
PortChannel4    128  4         Y   Y    Y                  DISABLED   0          0000000000000000
sonic(conf-if-Ethernet4)#

sonic(conf-if-Ethernet4)# do show spanning-tree bpdu-guard
PortNum          Shutdown    Port shut
                 Configured  due to BPDU guard
sonic(conf-if-Ethernet4)#

DELETE COMMANDS

sonic(conf-if-po4)# spanning-tree cost 100
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
21) "path_cost"
22) "100"
127.0.0.1:6379[4]> 
sonic(conf-if-po4)# no spanning-tree cost
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 1) "portfast"
 2) "true"
 3) "uplink_fast"
 4) "true"
 5) "link_type"
 6) "auto"
 7) "enabled"
 8) "true"
 9) "root_guard"
10) "false"
11) "bpdu_guard"
12) "false"
13) "bpdu_filter"
14) "global"
15) "bpdu_guard_do_disable"
16) "false"
17) "priority"
18) "10"
19) "edge_port"
20) "true"
127.0.0.1:6379[4]> 
Success

sonic(conf-if-po4)# spanning-tree bpdufilter enable
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
13) "bpdu_filter"
14) "enable"

sonic(conf-if-po4)# no spanning-tree bpdufilter
Success
sonic(conf-if-po4)#

127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
13) "bpdu_filter"
14) "global"

sonic(conf-if-po4)# spanning-tree guard root
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 9) "root_guard"
10) "true"

sonic(conf-if-po4)# no spanning-tree guard root
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 9) "root_guard"
10) "false"

sonic(conf-if-po4)# spanning-tree link-type shared
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 5) "link_type"
 6) "shared"

sonic(conf-if-po4)# no spanning-tree link-type
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 5) "link_type"
 6) "auto"

sonic(conf-if-po4)# spanning-tree port type edge
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
19) "edge_port"
20) "true"

sonic(conf-if-po4)# no spanning-tree port type
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
19) "edge_port"
20) "false"

sonic(conf-if-po4)# spanning-tree port-priority 123
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
17) "priority"
18) "123"

sonic(conf-if-po4)# no spanning-tree port-priority
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 1) "portfast"
 2) "true"
 3) "uplink_fast"
 4) "true"
 5) "link_type"
 6) "auto"
 7) "enabled"
 8) "true"
 9) "root_guard"
10) "false"
11) "bpdu_guard"
12) "false"
13) "bpdu_filter"
14) "global"
15) "bpdu_guard_do_disable"
16) "true"
17) "edge_port"
18) "false"

sonic(conf-if-po4)# spanning-tree portfast
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 1) "portfast"
 2) "true"

sonic(conf-if-po4)# no spanning-tree portfast
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 1) "portfast"
 2) "false"

sonic(conf-if-po4)# spanning-tree uplinkfast
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 3) "uplink_fast"
 4) "true"

sonic(conf-if-po4)# no spanning-tree uplinkfast
Success
127.0.0.1:6379[4]> hgetall "STP_PORT|PortChannel4"
 3) "uplink_fast"
 4) "false"

~~~

### CODE REVIEW

**Comment by bhavini-gada** [comment]
Could you please attach the command-tree output as well ?

**Comment by jeffyin-dell** [comment]
Please update the title of this PR to be more descriptive, and remove the internal JIRA identifiers.

**Comment by spenugondaa** [comment]
> Could you please attach the command-tree output as well ?

Done

**Comment by spenugondaa** [comment]
> Please update the title of this PR to be more descriptive, and remove the internal JIRA identifiers.

Done

**Review by joyas-joseph — APPROVED** [review]

**Pull request merged**
