### PR TITLE
CVL changes for SONiC YANG

### PR DESCRIPTION
**Pull request by dutta-partha**

### CODE REVIEW

**Review by dutta-partha — COMMENTED** [review]
Looks good.

**Review by kwangsuk — COMMENTED** [review]
Thanks Partha. It looks good.
One comment is that we may need to add the "description" substatement where applicable, since these models will be shown as a reference point for writing new SONiC yang.

**Comment by dutta-partha** [comment]
Yes, we can as needed. We can add them in subsequent changes.

**Comment by kwangsuk** [comment]
@dutta-partha Transformer change must be merged together with this PR to avoid disruption. Currently Dell team is using the master branch for Buzznik feature development. Can we hold merging until next Monday?

**Review by kwangsuk — APPROVED** [review]
The transformer change has been made to support nee change. It will be merged after merging this PR.

**Pull request merged**
