### PR TITLE
SONiC RBAC

### PR DESCRIPTION
**Pull request by jeffyin-dell**
Phase 1 of the SONiC Role-Based Access Control (RBAC) feature for the SONiC Management Framework. 

The RBAC High-Level Design document can be found [here](https://github.com/project-arlo/SONiC/blob/master/doc/aaa/SONiC%20RBAC%20HLD.md).

### CODE REVIEW

**Review by martin-belanger — APPROVED** [review]
It looks good

**Review by arunsundark — APPROVED** [review]
Requested changes for CLI stuff. Will do a proper build and validate.

**Review by arunsundark — CHANGES_REQUESTED** [review]
Openconfig system annot file has some unwanted deviations. Will need to delete them.

**Comment by jeffyin-dell** [comment]
> Openconfig system annot file has some unwanted deviations. Will need to delete them.

@arunsundark  -- you can make these changes and the push them to the `sonic-rbac` branch. This PR will automatically update.

**Review by arunsundark — APPROVED** [review]

**Pull request merged**
