### PR TITLE
Add the missing lines from merge conflicts

### PR DESCRIPTION
**Pull request by kwangsuk**

### CODE REVIEW

**Review by dutta-partha — COMMENTED** [review]
These are steps for SONiC YANG and should not be there in cvl specific Makefile. We are planning to have such makefile in "models/yang/sonic/" folder where all SONiC YANG will be present.

**Comment by s-mari** [comment]
.

**Review by s-mari — APPROVED** [review]

**Review by dutta-partha — CHANGES_REQUESTED** [review]
Please see the comments posted. 
Please add these rules in a new Makefile specific to SONiC YANG. This makefile is for CVL YANG only.

**Comment by kwangsuk** [comment]
> Please see the comments posted.
> Please add these rules in a new Makefile specific to SONiC YANG. This makefile is for CVL YANG only.

I think your request is to move the rules to a new Makefile under "models/yang/sonic". But, I don't see the folder or Makefile yet in the master branch. Once the sonic folder is available, the rules will be moved there as requested.

**Review by dutta-partha — APPROVED** [review]
I am creating new folder structure for SONiC YANG. Will move the relevant Makefile rules from this file, then you can change further as needed. For now, I am approving the changes.

**Pull request merged**
