### PR TITLE
STP CLI show bug fixes 

### PR DESCRIPTION
**Pull request by mhampasagar**
Issue:
show spanning-tree command shows output for STP disabled VLANs
show spanning-tree bpdu-guard command shows output for bpdu_guard disable ports

Fix:
Added check for VLAN status before displaying.
Added check for bpdu guard status before displaying .
Added other minor fixes

Test output:

bpdu guard enabled

sonic(conf-if-Ethernet0)# do show spanning-tree bpdu-guard
PortNum          Shutdown    Port shut
                 Configured  due to BPDU guard
Ethernet0        N           NA

bpdu guard disabled

sonic(conf-if-Ethernet0)# do show spanning-tree bpdu-guard
PortNum          Shutdown    Port shut
                 Configured  due to BPDU guard

STP enbaled on Vlan 10 and Vlan 20

sonic(conf-if-Ethernet0)# do show spanning-tree
Spanning-tree Mode: RPVST

VLAN 10 - RSTP instance 0
------------------------------------------------------------------------------------------------------------

RSTP (IEEE 802.1w) Bridge Parameters:

Bridge            Bridge    Bridge    Bridge    tx
Identifier        MaxAge    Hello     FwdDly    Hold
hex               sec       sec       sec       cnt
800a90b11cf4abe0  20        2         15

RootBridge        RootPath  DesignatedBridge  Root        Max  Hel  Fwd
Identifier        Cost      Identifier        Port        Age  lo   Dly
hex                         hex                           sec  sec  sec
800a90b11cf4abe0  0         800a90b11cf4abe0              20   2    15

RSTP (IEEE 802.1w) Port Parameters:
Port            Prio Path      P2P Edge BPDU   Role      State      Designa-   Designated
Num             rity Cost      Mac Port Filter                      ted cost   bridge
Ethernet0       128  500       N   N    N                DISABLED   0          0000000000000000

VLAN 20 - RSTP instance 1
------------------------------------------------------------------------------------------------------------

--more--
RSTP (IEEE 802.1w) Bridge Parameters:

Bridge            Bridge    Bridge    Bridge    tx
Identifier        MaxAge    Hello     FwdDly    Hold
hex               sec       sec       sec       cnt
801490b11cf4abe0  20        2         15

RootBridge        RootPath  DesignatedBridge  Root        Max  Hel  Fwd
Identifier        Cost      Identifier        Port        Age  lo   Dly
hex                         hex                           sec  sec  sec
801490b11cf4abe0  0         801490b11cf4abe0              20   2    15

RSTP (IEEE 802.1w) Port Parameters:
Port            Prio Path      P2P Edge BPDU   Role      State      Designa-   Designated
Num             rity Cost      Mac Port Filter                      ted cost   bridge
Ethernet0       128  500       N   N    N                DISABLED   0          0000000000000000
sonic(conf-if-Ethernet0)#

With STP disabled on VLAN 10

sonic(conf-if-Ethernet0)# do show spanning-tree
Spanning-tree Mode: RPVST

VLAN 20 - RSTP instance 1
------------------------------------------------------------------------------------------------------------

RSTP (IEEE 802.1w) Bridge Parameters:

Bridge            Bridge    Bridge    Bridge    tx
Identifier        MaxAge    Hello     FwdDly    Hold
hex               sec       sec       sec       cnt
801490b11cf4abe0  20        2         15

RootBridge        RootPath  DesignatedBridge  Root        Max  Hel  Fwd
Identifier        Cost      Identifier        Port        Age  lo   Dly
hex                         hex                           sec  sec  sec
801490b11cf4abe0  0         801490b11cf4abe0              20   2    15

RSTP (IEEE 802.1w) Port Parameters:
Port            Prio Path      P2P Edge BPDU   Role      State      Designa-   Designated
Num             rity Cost      Mac Port Filter                      ted cost   bridge
Ethernet0       128  500       N   N    N                DISABLED   0          0000000000000000
sonic(conf-if-Ethernet0)# do show spanning-tree counters

VLAN 20 - RSTP instance 1
--------------------------------------------------------------------------------
PortNum         BPDU Tx   BPDU Rx   Config BPDU Config BPDU
                                    Tx          Rx
--------------------------------------------------------------------------------
Ethernet0       0         0         0           0
sonic(conf-if-Ethernet0)#

### CODE REVIEW

**Comment by joyas-joseph** [comment]
Could you please attach sample  output?

**Comment by mhampasagar** [comment]
> Could you please attach sample output?

Attached the output .
(Note: as of now the images I have yesterdays official image, most of the STP config commands are failing using sonic-CLI, I verified my fixes with using CLIK CLI)

**Review by jeffyin-dell — CHANGES_REQUESTED** [review]
Please provide a more descriptive title for the commit message. "Bug fixes for Bug" is hard to interpret...
Also, please avoid using internal JIRA IDs when contributing code to this open source project; readers will not know what they're for. 

Alternatively, this can be addressed during merge, when we squash/merge this PR we can modify the commit message. @joyas-joseph Let's make sure that the commit message doesn't contain the Jira IDs at least. :)

**Comment by mhampasagar** [comment]
> Please provide a more descriptive title for the commit message. "Bug fixes for Bug" is hard to interpret...
> Also, please avoid using internal JIRA IDs when contributing code to this open source project; readers will not know what they're for.
> 
> Alternatively, this can be addressed during merge, when we squash/merge this PR we can modify the commit message. @joyas-joseph Let's make sure that the commit message doesn't contain the Jira IDs at least. :)

Updated title and description.

About the JIRA ID's , if we do not want to mention then these has to github issues instead of JIRA's, otherwise how to track what fix went in to these JIRA's

**Review by jeffyin-dell — APPROVED** [review]

**Review by joyas-joseph — APPROVED** [review]

**Pull request merged**
