### PR TITLE
Transformer merge

### PR DESCRIPTION
**Pull request by PrabhuSreenivasan**

### CODE REVIEW

**Review by kwangsuk — COMMENTED** [review]
The changes look good.
One comment is that I can't see the patch file. Did you make one?

**Comment by PrabhuSreenivasan** [comment]
I did undo the patch file deletion on this branch. Its not showing up on the PR as the patch file is already present on the release_1.0 branch and no changes on that file as part of this PR.

**Comment by kwangsuk** [comment]
> I did undo the patch file deletion on this branch. Its not showing up on the PR as the patch file is already present on the release_1.0 branch and no changes on that file as part of this PR.

Hi Prabhu,
Ok. Some changes were made to fix handling the leaf-list from the transformer phase2. I just want to know that the patch was made based on new code changes.

**Comment by kwangsuk** [comment]
> I did undo the patch file deletion on this branch. Its not showing up on the PR as the patch file is already present on the release_1.0 branch and no changes on that file as part of this PR.

Hi Prabhu,
Ok. Some changes were made to fix handling the leaf-list from the transformer phase2. I just want to know that the patch was made based on new code changes.

**Comment by PrabhuSreenivasan** [comment]
Thanks for bringing it up. I have not taken care of any new ygot patches introduced on transformer-phase2. Bala maybe able to help us here

**Pull request merged**
